config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :pictures
  resources :videos
  resources :instagrams

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  validates_presence_of :url, message: "URL cannot be blank"
  validates_presence_of :description, message: "Description cannot be blank"
  validates_length_of :description, maximum: 255, message: "Description cannot be longer than 255 characters"

  validates :url,
            format: {
              with: /(png|gif|jpg|jpeg)\Z/,
              message: "URL must be valid"
            }
end

app/models/video.rb
class Video < ActiveRecord::Base
  validates_presence_of :url, message: "URL cannot be blank"
  validates_presence_of :description, message: "Description cannot be blank"
  validates_length_of :description, maximum: 255, message: "Description cannot be longer than 255 characters"

  validates :url,
            format: {
              with: /watch\?v=.{11}\Z/,
              message: "URL must be valid"
            }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/instagrams_controller.rb
class InstagramsController <ApplicationController
  require "instagram"
  require 'pp'

  CALLBACK_URL = "http://localhost:4567/oauth/callback"

  Instagram.configure do |config|
    config.client_id = ENV['CLIENT_ID']
    config.client_secret = ENV['CLIENT_SECRET']
  end

  def index
    
    @html = Instagram.media_search("40.0176335","-105.2819911")

  end


end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(allowed_parameters)
    if @picture.save
      redirect_to picture_path(@picture), :flash => {:success => "Picture successfully created"}
    else
      @picture
      render new_picture_path
    end
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.update(params[:id], allowed_parameters)
    if @picture.valid?
      redirect_to picture_path
    else
      @picture
      render :edit
    end
  end

  def destroy
    @picture = Picture.find_by_id params[:id]
    @picture.delete
    redirect_to pictures_path, :flash => {:success => "Picture successfully deleted"}
  end

  private

  def allowed_parameters
    params.permit(:id, :url, :description, :rating)
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
    @videos = Video.all
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(
      url: params[:video_url],
      description: params[:video_description],
      rating: params[:video_rating]
    )
    if @video.save
      redirect_to "/videos/#{@video.id}", :flash => {:success => "Video successfully created"}
    else
      @video
      render :action => "new"
    end
  end

  def show
    @video = Video.find_by_id params[:id]
  end

  def edit
    @video = Video.find_by_id params[:id]
  end

  def update
    @video = Video.update(params[:id],
                          url: params[:video_url],
                          description: params[:video_description],
                          rating: params[:video_rating]
    )
    if @video.valid?
      redirect_to video_path
    else
      @video
      render :edit
    end
  end

  def destroy
    @video = Video.find_by_id params[:id]
    @video.delete
    redirect_to videos_path, :flash => {:success => "Video successfully deleted"}
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/instagrams/index.html.erb
<h1>Instagram Photos</h1>

<div id="instagram_container">
  <% @html.each do |image| %>
      <div id="instagram_image">
        <% if request.user_agent.include?('iPhone') %>
            <a href="instagram://media?id=<%= image.id %>"><img src="<%= image.images.thumbnail.url %>"></a>
        <% else %>
            <a href="<%= image.link %>"><img src="<%= image.images.thumbnail.url %>"></a>
        <% end %>
        <a href="http://instagram.com/<%= image.user.username %>"><%= image.user.username %></a>
        <% if image.caption != nil %>
            <br><%= image.caption.text %>
        <% end %>
      </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Media Manager</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <div class="headerfootercontainer">
    <div class="headfootalign">
      <div id="headertitle">
        <a href="/"><h1>Media Manager</h1></a>
      </div>
    </div>
    <div id="nav_links"><a href="/pictures">all pictures</a> | <a href="/videos">all videos</a>
    </div>
  </div>
</header>
<div id="bodycontainer">
  <div id="bodycontent">
    <%= yield %>
  </div>
</div>
<footer>
  <div class="headerfootercontainer">
    <div class="headfootalign">
      <div id="footertext">Not copyrighted at all</div>
    </div>
  </div>
</footer>
</body>

</html>

app/views/pictures/edit.html.erb
<h1>Edit picture</h1>
<% if @picture.errors.present? %>
    <ul>
      <% @picture.errors.messages.each do |message| %>
          <li class="error_message"><%= message[1][0] %></li>
      <% end %>
    </ul>
<% end %>
<form class="crud_form" action="<%= picture_path %>" method="post">
  <table>
    <input type="hidden" name="_method" value="put">
    <tr>
      <td><input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"></td>
      <td></td>
    </tr>
    <tr>
      <td><label for="url">URL of Picture</label></td>
      <td><input type="text" name="url" value="<%= @picture.url %>"></td>
    </tr>
    <tr>
      <td><label for="description">Short Description</label></td>
      <td><textarea name="description"><%= @picture.description %></textarea></td>
    </tr>
    <tr>
      <td><label for="rating">Rating</label></td>
      <td><input id="rating" type="number" max="5" min="0" name="rating" value="<%= @picture.rating %>"></td>
    </tr>
    <tr>
      <td>
        <button type="submit">Update Picture</button>
      </td>
      <td></td>
    </tr>
  </table>
</form>

app/views/pictures/index.html.erb
<p id="flash_success"><%= flash[:success] %></p>
<h1>Pictures</h1>
<a href="/pictures/new">New Picture</a>
  <div id="images">
    <% @pictures.each do |picture| %>
      <a href="pictures/<%= picture.id %>"><img src="<%= picture.url %>"></a>
    <% end %>
  </div>
</div>

app/views/pictures/new.html.erb
<h1>Add a picture</h1>
<% if @picture.errors.present? %>
  <ul>
    <% @picture.errors.messages.each do |message| %>
      <li class="error_message"><%= message[1][0] %></li>
    <% end %>
  </ul>
<% end %>
<table>
  <form class="crud_form" action="<%= pictures_path %>" method="post">
    <tr>
      <td><input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"></td>
      <td></td>
    </tr>
    <tr>
      <td><label for="url">URL of Picture</label></td>
      <td><input type="text" name="url" value="<%= @picture.url %>"></td>
    </tr>
    <tr>
      <td><label for="description">Short Description</label></td>
      <td><textarea name="description"><%= @picture.description %></textarea></td>
    </tr>
    <tr>
      <td><label for="rating">Rating</label></td>
      <td><input id="rating" type="number" max="5" min="0" name="rating" value="<%= @picture.rating %>"></td>
    </tr>
    <tr>
      <td>
        <button type="submit">Create Picture</button>
      </td>
      <td></td>
    </tr>
  </form>
</table>

app/views/pictures/show.html.erb
<div id="show_left">
  <img src="<%= @picture.url %>">
  <p>Rating: <%= @picture.rating %> out of 5</p>
</div>

<div id="show_right">
  <p id="flash_success"><%= flash[:success] %></p>
  <a href="<%= @picture.url %>"><%= @picture.url %></a>
  <%= link_to "(Edit)", edit_picture_path %>
  <p id="show_description"><%= @picture.description %></p>
  <div id="delete_button">
    <form action="<%= picture_path %>" method="post">
      <input type="hidden" name="_method" value="delete">
      <button type="submit">Delete Picture</button>
    </form>
  </div>
</div>

app/views/videos/edit.html.erb
<h1>Edit Video</h1>
<% if @video.errors.messages.present? %>
    <ul>
      <% @video.errors.messages.each do |k, v| %>
          <li class="error_message"><%= v.first %></li>
      <% end %>
    </ul>
<% end %>
<form action="<%=video_path%>" method="post">
  <table>
    <input type="hidden" name="_method" value="put">
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
    <tr>
      <td style="width: 12em">URL of Video</td>
      <td><input style="width: 25em" type="text" name="video_url" autofocus="autofocus" value="<%= @video.url %>"></td>
    </tr>
    <br>
    <tr>
      <td>Short Description</td>
      <td>
        <textarea style="margin-top: 0;width: 25em;height: 5em" name="video_description"><%= @video.description %></textarea>
      </td>
    </tr>
    <br>
    <tr>
      <td>Rating</td>
      <td><input style="width: 30%" type="number" max="5" min="0" name="video_rating" value="<%= @video.rating %>"></td>
    </tr>
    <br>
    <tr>
      <td>
        <button type="submit">Update Video</button>
      </td>
    </tr>
  </table>
</form>

app/views/videos/index.html.erb
<p id="flash_success"><%= flash[:success] %></p>
<h1>Videos</h1>
<%= link_to "New Video", new_video_path %>
<br>

<% @videos.each do |video| %>
    <div id="video_links">
      <a href="/videos/<%= video.id %>"><%= video.url %></a>
    </div>
<% end %>

app/views/videos/new.html.erb
<h1>Add a Video</h1>
<% if @video.errors.messages.present? %>
    <ul>
      <% @video.errors.messages.each do |k, v| %>
          <li class="error_message"><%= v.first %></li>
      <% end %>
    </ul>
<% end %>
<table>
  <form action="/videos" method="post">
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
    <tr>
      <td style="width: 12em">URL of Video</td>
      <td><input style="width: 25em" type="text" name="video_url" autofocus="autofocus" value="<%= @video.url %>"></td>
    </tr>
    <br>
    <tr>
      <td>Short Description</td>
      <td>
        <textarea style="margin-top: 0;width: 25em;height: 5em" name="video_description"><%= @video.description %></textarea>
      </td>
    </tr>
    <br>
    <tr>
      <td>Rating</td>
      <td><input style="width: 30%" type="number" max="5" min="0" name="video_rating" value="<%= @video.rating %>"></td>
    </tr>
    <br>
    <tr>
      <td>
        <button type="submit">Create Video</button>
      </td>
    </tr>
  </form>
</table>

app/views/videos/show.html.erb
<% p = URI.parse(@video.url) %>
<% u = CGI.parse(p.query) %>
<div id="show_left">
  <iframe width="450" height="300" src="//www.youtube.com/embed/<%= u["v"].first %>" frameborder="0" allowfullscreen></iframe>
  <p>Rating: <%= @video.rating %> out of 5</p>
</div>

<div id="show_right">
  <p id="flash_success"><%= flash[:success] %></p>
  <a href="<%= @video.url %>"><%= @video.url %></a>
  <%= link_to "(Edit)", edit_video_path %>
  <p id="show_description"><%= @video.description %></p>

  <div id="delete_button">
    <form action="<%= video_path %>" method="post">
      <input type="hidden" name="_method" value="delete">
      <button type="submit">Delete Video</button>
    </form>
  </div>
</div>

app/views/welcome/index.html.erb
<p>Welcome to the media manager, where you can, well... manage media.</p>

<div id="show_left">
<h1>Pictures!</h1>
  <%= link_to "View All", pictures_path %><br><br>
  <%= link_to "Add New", new_picture_path %>
<h1>Instagram!</h1>
  <%= link_to "View Instagram Photos", instagrams_path %>
</div>

<div id="show_right">
  <h1>Videos!</h1>
  <%= link_to "View All", videos_path %><br><br>
  <%= link_to "Add New", new_video_path %>
</div>